#include "client.h"
#include <QSqlError>
#include <QDebug>

Client::Client(int id, QString nom, QString type, QString tel,
               QString email, QString statut, QString adresse)
{
    this->id      = id;
    this->nom     = nom;
    this->type    = type;
    this->tel     = tel;
    this->email   = email;
    this->statut  = statut;
    this->adresse = adresse;
}

// ─── CREATE ───────────────────────────────────────────────────────────────────
bool Client::ajouter()
{
    QSqlQuery query;
    query.prepare(
        "INSERT INTO CLIENT (NOM_CLIENT, TELEPHONE, EMAIL, ADRESSE, TYPE_CLIENT, STATUT) "
        "VALUES (:nom, :tel, :email, :adresse, :type, :statut)"
    );
    // ID_CLIENT is auto-generated by the trigger + sequence
    query.bindValue(":nom",     nom);
    query.bindValue(":tel",     tel);
    query.bindValue(":email",   email);
    query.bindValue(":adresse", adresse);
    query.bindValue(":type",    type);
    query.bindValue(":statut",  statut);

    bool ok = query.exec();
    if (!ok)
        qDebug() << "[CLIENT] ajouter() ERROR:" << query.lastError().text();
    return ok;
}

// ─── DELETE ───────────────────────────────────────────────────────────────────
bool Client::supprimer(int id)
{
    QSqlQuery query;
    query.prepare("DELETE FROM CLIENT WHERE ID_CLIENT = :id");
    query.bindValue(":id", id);

    bool ok = query.exec();
    if (!ok)
        qDebug() << "[CLIENT] supprimer() ERROR:" << query.lastError().text();
    return ok;
}

// ─── UPDATE ───────────────────────────────────────────────────────────────────
bool Client::modifier()
{
    QSqlQuery query;
    query.prepare(
        "UPDATE CLIENT SET "
        "  NOM_CLIENT  = :nom,  "
        "  TELEPHONE   = :tel,  "
        "  EMAIL       = :email, "
        "  ADRESSE     = :adresse, "
        "  TYPE_CLIENT = :type, "
        "  STATUT      = :statut "
        "WHERE ID_CLIENT = :id"
    );
    query.bindValue(":nom",     nom);
    query.bindValue(":tel",     tel);
    query.bindValue(":email",   email);
    query.bindValue(":adresse", adresse);
    query.bindValue(":type",    type);
    query.bindValue(":statut",  statut);
    query.bindValue(":id",      id);

    bool ok = query.exec();
    if (!ok)
        qDebug() << "[CLIENT] modifier() ERROR:" << query.lastError().text();
    return ok;
}

// ─── READ (all) ───────────────────────────────────────────────────────────────
QSqlQueryModel* Client::afficher()
{
    QSqlQueryModel* model = new QSqlQueryModel();
    model->setQuery(
        "SELECT ID_CLIENT, NOM_CLIENT, TYPE_CLIENT, TELEPHONE, EMAIL, STATUT "
        "FROM CLIENT ORDER BY ID_CLIENT"
    );
    model->setHeaderData(0, Qt::Horizontal, QObject::tr("ID"));
    model->setHeaderData(1, Qt::Horizontal, QObject::tr("Nom"));
    model->setHeaderData(2, Qt::Horizontal, QObject::tr("Type"));
    model->setHeaderData(3, Qt::Horizontal, QObject::tr("Téléphone"));
    model->setHeaderData(4, Qt::Horizontal, QObject::tr("Email"));
    model->setHeaderData(5, Qt::Horizontal, QObject::tr("Statut"));

    if (model->lastError().isValid())
        qDebug() << "[CLIENT] afficher() ERROR:" << model->lastError().text();
    return model;
}

// ─── READ (filtered) ──────────────────────────────────────────────────────────
QSqlQueryModel* Client::rechercher(QString nom, QString type, QString statut)
{
    QSqlQueryModel* model = new QSqlQueryModel();

    QString sql =
        "SELECT ID_CLIENT, NOM_CLIENT, TYPE_CLIENT, TELEPHONE, EMAIL, STATUT "
        "FROM CLIENT WHERE 1=1";

    if (!nom.isEmpty())
        sql += " AND UPPER(NOM_CLIENT) LIKE UPPER('%" + nom + "%')";
    if (type != "Tous" && !type.isEmpty())
        sql += " AND TYPE_CLIENT = '" + type + "'";
    if (statut != "Tous" && !statut.isEmpty())
        sql += " AND STATUT = '" + statut + "'";

    sql += " ORDER BY ID_CLIENT";
    model->setQuery(sql);

    model->setHeaderData(0, Qt::Horizontal, QObject::tr("ID"));
    model->setHeaderData(1, Qt::Horizontal, QObject::tr("Nom"));
    model->setHeaderData(2, Qt::Horizontal, QObject::tr("Type"));
    model->setHeaderData(3, Qt::Horizontal, QObject::tr("Téléphone"));
    model->setHeaderData(4, Qt::Horizontal, QObject::tr("Email"));
    model->setHeaderData(5, Qt::Horizontal, QObject::tr("Statut"));

    if (model->lastError().isValid())
        qDebug() << "[CLIENT] rechercher() ERROR:" << model->lastError().text();
    return model;
}
