--------------------------------------------------------
--  Fichier créé - samedi-mars-28-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE "SMARTOIL"."EMPLOYE" 
   (	"ID_EMPLOYE" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"AGE" NUMBER, 
	"SALAIRE" NUMBER, 
	"POSTE" VARCHAR2(20 BYTE), 
	"ANCIENNETE" NUMBER, 
	"DISPONIBILITE" VARCHAR2(20 BYTE), 
	"HEURES_TRAVAIL" NUMBER, 
	"FOURNISSEURS_TRAITES" NUMBER, 
	"ID_EQUIPE" NUMBER, 
	"MDP" VARCHAR2(255 BYTE), 
	"RESET_CODE" VARCHAR2(10 BYTE), 
	"RESET_CODE_EXPIRATION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMMENDE
--------------------------------------------------------

  CREATE TABLE "SMARTOIL"."COMMENDE" 
   (	"ID_COMMANDE" NUMBER, 
	"LIBELLE" VARCHAR2(20 BYTE), 
	"DATE_ARRIVAGE" DATE, 
	"DATE_SORTIE" DATE, 
	"ETAT" VARCHAR2(20 BYTE), 
	"QUANTITE" NUMBER, 
	"MONTANT_TOTAL" NUMBER, 
	"ID_CLIENT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "SMARTOIL"."CLIENT" 
   (	"ID_CLIENT" NUMBER, 
	"NOM_CLIENT" VARCHAR2(20 BYTE), 
	"T?L?PHONE" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"ADRESSE" VARCHAR2(200 BYTE), 
	"TYPE_CLIENT" VARCHAR2(20 BYTE), 
	"STATUT" VARCHAR2(20 BYTE), 
	"ID_EMPLOYE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EQUIPE
--------------------------------------------------------

  CREATE TABLE "SMARTOIL"."EQUIPE" 
   (	"ID_EQUIPE" NUMBER, 
	"NOM_EQUIPE" VARCHAR2(20 BYTE), 
	"SPECIALITE" VARCHAR2(20 BYTE), 
	"NBRE_MEMBRES" NUMBER, 
	"ETAT" VARCHAR2(20 BYTE), 
	"RATE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LABO
--------------------------------------------------------

  CREATE TABLE "SMARTOIL"."LABO" 
   (	"ID_LABO" NUMBER, 
	"NOM_LABO" VARCHAR2(20 BYTE), 
	"RESULTATS" VARCHAR2(200 BYTE), 
	"CONFORMITE" CHAR(3 BYTE), 
	"ADRESSE" VARCHAR2(200 BYTE), 
	"ESPACE_LABO" NUMBER, 
	"ESPACE_RESTE" NUMBER, 
	"REVIEW" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MACHINES
--------------------------------------------------------

  CREATE TABLE "SMARTOIL"."MACHINES" 
   (	"ID_MACHINE" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"CATEGORIE" VARCHAR2(20 BYTE), 
	"REFERENCE" VARCHAR2(20 BYTE), 
	"DATE_ACHAT" DATE, 
	"ETAT_ACHAT" VARCHAR2(20 BYTE), 
	"LOCALISATION" VARCHAR2(150 BYTE), 
	"DATE_FIN_GARENTIE" DATE, 
	"ID_LABO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UTILISER
--------------------------------------------------------

  CREATE TABLE "SMARTOIL"."UTILISER" 
   (	"ID_EQUIPE" NUMBER, 
	"ID_MATRIEL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into SMARTOIL.EMPLOYE
SET DEFINE OFF;
Insert into SMARTOIL.EMPLOYE (ID_EMPLOYE,NOM,PRENOM,AGE,SALAIRE,POSTE,ANCIENNETE,DISPONIBILITE,HEURES_TRAVAIL,FOURNISSEURS_TRAITES,ID_EQUIPE,MDP,RESET_CODE,RESET_CODE_EXPIRATION) values ('3','you','bsaid','44','2500','Magasinier','20','suspendu','0','55',null,'882c2f8f856e2f93fdde7d25631bb887d6d680b669f9a0affd80ef573cb9a8b4',null,null);
Insert into SMARTOIL.EMPLOYE (ID_EMPLOYE,NOM,PRENOM,AGE,SALAIRE,POSTE,ANCIENNETE,DISPONIBILITE,HEURES_TRAVAIL,FOURNISSEURS_TRAITES,ID_EQUIPE,MDP,RESET_CODE,RESET_CODE_EXPIRATION) values ('4','alou','alou','22','3500','Manager','9','actif','35','29',null,'b83e0b5224e88892d43879f6bf6c642a985712bd027cd14791868eed8f8a8c7d',null,null);
Insert into SMARTOIL.EMPLOYE (ID_EMPLOYE,NOM,PRENOM,AGE,SALAIRE,POSTE,ANCIENNETE,DISPONIBILITE,HEURES_TRAVAIL,FOURNISSEURS_TRAITES,ID_EQUIPE,MDP,RESET_CODE,RESET_CODE_EXPIRATION) values ('5','salim','wiw','25','750','Magasinier','1','actif','60','5',null,'f608b7f1781fe661c47ef546a383a4de4b960b87303bec9e3815ee3b0d6817f8',null,null);
Insert into SMARTOIL.EMPLOYE (ID_EMPLOYE,NOM,PRENOM,AGE,SALAIRE,POSTE,ANCIENNETE,DISPONIBILITE,HEURES_TRAVAIL,FOURNISSEURS_TRAITES,ID_EQUIPE,MDP,RESET_CODE,RESET_CODE_EXPIRATION) values ('6','salim','alou','24','1000','Technicien','2','actif','20','12',null,'111d44284709558c2f633bfe8e0bf491a6cb47127ff1ecf7d40c1c6a035ffad3',null,null);
Insert into SMARTOIL.EMPLOYE (ID_EMPLOYE,NOM,PRENOM,AGE,SALAIRE,POSTE,ANCIENNETE,DISPONIBILITE,HEURES_TRAVAIL,FOURNISSEURS_TRAITES,ID_EQUIPE,MDP,RESET_CODE,RESET_CODE_EXPIRATION) values ('1','Aloui','Salmene','20','5000','Admin','7','actif','70','40',null,'de35760c8a87428963cf1dce12ed348c7420bf431c35abef53e74b90286dde82',null,null);
Insert into SMARTOIL.EMPLOYE (ID_EMPLOYE,NOM,PRENOM,AGE,SALAIRE,POSTE,ANCIENNETE,DISPONIBILITE,HEURES_TRAVAIL,FOURNISSEURS_TRAITES,ID_EQUIPE,MDP,RESET_CODE,RESET_CODE_EXPIRATION) values ('2','aloui','sisou','27','2500','Technicien','1','actif','20','0',null,'26765e3850508fefd8e1592d56f746b8fa738d3a3f19b339c6777a8a7767ccdd',null,null);
Insert into SMARTOIL.EMPLOYE (ID_EMPLOYE,NOM,PRENOM,AGE,SALAIRE,POSTE,ANCIENNETE,DISPONIBILITE,HEURES_TRAVAIL,FOURNISSEURS_TRAITES,ID_EQUIPE,MDP,RESET_CODE,RESET_CODE_EXPIRATION) values ('7','cherif','ayoub','18','500005','Admin','5','actif','0','0',null,'a5c8ca924b318636a496131474a0f54fa1bf5ce60a3e608bcf81a1cefb4d29a5',null,null);
REM INSERTING into SMARTOIL.COMMENDE
SET DEFINE OFF;
REM INSERTING into SMARTOIL.CLIENT
SET DEFINE OFF;
Insert into SMARTOIL.CLIENT (ID_CLIENT,NOM_CLIENT,"T?L?PHONE",EMAIL,ADRESSE,TYPE_CLIENT,STATUT,ID_EMPLOYE) values ('1','Ali Ben Salah',null,null,null,null,null,null);
Insert into SMARTOIL.CLIENT (ID_CLIENT,NOM_CLIENT,"T?L?PHONE",EMAIL,ADRESSE,TYPE_CLIENT,STATUT,ID_EMPLOYE) values ('2','Sami Trabelsi',null,null,null,null,null,null);
Insert into SMARTOIL.CLIENT (ID_CLIENT,NOM_CLIENT,"T?L?PHONE",EMAIL,ADRESSE,TYPE_CLIENT,STATUT,ID_EMPLOYE) values ('3','Amira Jlassi',null,null,null,null,null,null);
Insert into SMARTOIL.CLIENT (ID_CLIENT,NOM_CLIENT,"T?L?PHONE",EMAIL,ADRESSE,TYPE_CLIENT,STATUT,ID_EMPLOYE) values ('4','Karim Gharbi',null,null,null,null,null,null);
Insert into SMARTOIL.CLIENT (ID_CLIENT,NOM_CLIENT,"T?L?PHONE",EMAIL,ADRESSE,TYPE_CLIENT,STATUT,ID_EMPLOYE) values ('5','Nour Ben Ali',null,null,null,null,null,null);
REM INSERTING into SMARTOIL.EQUIPE
SET DEFINE OFF;
REM INSERTING into SMARTOIL.LABO
SET DEFINE OFF;
Insert into SMARTOIL.LABO (ID_LABO,NOM_LABO,RESULTATS,CONFORMITE,ADRESSE,ESPACE_LABO,ESPACE_RESTE,REVIEW) values ('3','azsaad','sasasas','non','sasasa','60','0','7');
Insert into SMARTOIL.LABO (ID_LABO,NOM_LABO,RESULTATS,CONFORMITE,ADRESSE,ESPACE_LABO,ESPACE_RESTE,REVIEW) values ('1','QHUDQIDGUQDIUQaaaaaa','qdfqiufqhyuf','oui','18 rue  sq','1500','600','4');
Insert into SMARTOIL.LABO (ID_LABO,NOM_LABO,RESULTATS,CONFORMITE,ADRESSE,ESPACE_LABO,ESPACE_RESTE,REVIEW) values ('2','zfbqfjqb','skpodJ','oui','SDSS','20','0','7');
Insert into SMARTOIL.LABO (ID_LABO,NOM_LABO,RESULTATS,CONFORMITE,ADRESSE,ESPACE_LABO,ESPACE_RESTE,REVIEW) values ('4','dzqdq','dqqdqdq','oui','qdqdq','880','0','9');
Insert into SMARTOIL.LABO (ID_LABO,NOM_LABO,RESULTATS,CONFORMITE,ADRESSE,ESPACE_LABO,ESPACE_RESTE,REVIEW) values ('5','dzfqqd','qscqc','oui','daad','90','0','8');
Insert into SMARTOIL.LABO (ID_LABO,NOM_LABO,RESULTATS,CONFORMITE,ADRESSE,ESPACE_LABO,ESPACE_RESTE,REVIEW) values ('6','monir','parfais','oui','18 rue manzah','600','0','1');
REM INSERTING into SMARTOIL.MACHINES
SET DEFINE OFF;
REM INSERTING into SMARTOIL.UTILISER
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index EMPLOYE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SMARTOIL"."EMPLOYE_PK" ON "SMARTOIL"."EMPLOYE" ("ID_EMPLOYE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COMMENDE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SMARTOIL"."COMMENDE_PK" ON "SMARTOIL"."COMMENDE" ("ID_COMMANDE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CLIENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SMARTOIL"."CLIENTS_PK" ON "SMARTOIL"."CLIENT" ("ID_CLIENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TABLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SMARTOIL"."TABLE_PK" ON "SMARTOIL"."EQUIPE" ("ID_EQUIPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SMARTOIL"."TABLE1_PK" ON "SMARTOIL"."LABO" ("ID_LABO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MACHINES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SMARTOIL"."MACHINES_PK" ON "SMARTOIL"."MACHINES" ("ID_MACHINE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UTILISER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SMARTOIL"."UTILISER_PK" ON "SMARTOIL"."UTILISER" ("ID_MATRIEL", "ID_EQUIPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Trigger EMPLOYE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SMARTOIL"."EMPLOYE_TRG" 
BEFORE INSERT ON EMPLOYE
FOR EACH ROW
BEGIN
  SELECT EMPLOYE_SEQ.NEXTVAL
  INTO :NEW.ID_EMPLOYE
  FROM DUAL;
END;


/
ALTER TRIGGER "SMARTOIL"."EMPLOYE_TRG" ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "SMARTOIL"."EMPLOYE" ADD CONSTRAINT "EMPLOYE_CHK2" CHECK (poste IN ('Admin', 'Manager', 'Technicien', 'Magasinier')) ENABLE;
  ALTER TABLE "SMARTOIL"."EMPLOYE" ADD CONSTRAINT "EMPLOYE_CHK1" CHECK (disponibilite IN ('actif', 'suspendu')) ENABLE;
  ALTER TABLE "SMARTOIL"."EMPLOYE" ADD CONSTRAINT "EMPLOYE_PK" PRIMARY KEY ("ID_EMPLOYE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SMARTOIL"."EMPLOYE" MODIFY ("ID_EMPLOYE" NOT NULL ENABLE);
  ALTER TABLE "SMARTOIL"."EMPLOYE" MODIFY ("MDP" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMENDE
--------------------------------------------------------

  ALTER TABLE "SMARTOIL"."COMMENDE" ADD CONSTRAINT "COMMENDE_ETAT_CHECK" CHECK (ETAT IN ('en cours','validee','prete','annulee','livree')) ENABLE;
  ALTER TABLE "SMARTOIL"."COMMENDE" ADD CONSTRAINT "COMMENDE_CHK1" CHECK (ETAT IN ('en cours','validee','prete','annulee','livree')) ENABLE;
  ALTER TABLE "SMARTOIL"."COMMENDE" ADD CONSTRAINT "COMMENDE_PK" PRIMARY KEY ("ID_COMMANDE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SMARTOIL"."COMMENDE" MODIFY ("ID_COMMANDE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "SMARTOIL"."CLIENT" ADD CONSTRAINT "CLIENTS_CHK2" CHECK (statut IN ('actif', 'blacklist?')) ENABLE;
  ALTER TABLE "SMARTOIL"."CLIENT" ADD CONSTRAINT "CLIENTS_CHK1" CHECK (type_client IN ('beaut?', 'alimentaire')) ENABLE;
  ALTER TABLE "SMARTOIL"."CLIENT" ADD CONSTRAINT "CLIENTS_PK" PRIMARY KEY ("ID_CLIENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SMARTOIL"."CLIENT" MODIFY ("ID_CLIENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EQUIPE
--------------------------------------------------------

  ALTER TABLE "SMARTOIL"."EQUIPE" ADD CONSTRAINT "EQUIPE_CHK2" CHECK (etat IN ('active','inactive')) ENABLE;
  ALTER TABLE "SMARTOIL"."EQUIPE" ADD CONSTRAINT "EQUIPE_CHK1" CHECK (specialite IN ('maintenance','production','mecanique','backoffice')) ENABLE;
  ALTER TABLE "SMARTOIL"."EQUIPE" ADD CONSTRAINT "TABLE_PK" PRIMARY KEY ("ID_EQUIPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SMARTOIL"."EQUIPE" MODIFY ("SPECIALITE" NOT NULL ENABLE);
  ALTER TABLE "SMARTOIL"."EQUIPE" MODIFY ("ID_EQUIPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LABO
--------------------------------------------------------

  ALTER TABLE "SMARTOIL"."LABO" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ID_LABO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SMARTOIL"."LABO" ADD CONSTRAINT "TABLE1_CHK1" CHECK ("CONFORMITE"='oui' OR "CONFORMITE"='non') ENABLE;
  ALTER TABLE "SMARTOIL"."LABO" MODIFY ("CONFORMITE" NOT NULL ENABLE);
  ALTER TABLE "SMARTOIL"."LABO" MODIFY ("NOM_LABO" NOT NULL ENABLE);
  ALTER TABLE "SMARTOIL"."LABO" MODIFY ("ID_LABO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MACHINES
--------------------------------------------------------

  ALTER TABLE "SMARTOIL"."MACHINES" MODIFY ("ID_LABO" NOT NULL ENABLE);
  ALTER TABLE "SMARTOIL"."MACHINES" ADD CONSTRAINT "MACHINES_CHK2" CHECK ("ETAT_ACHAT"='en service' OR "ETAT_ACHAT"='panne' OR "ETAT_ACHAT"='maintenance' OR "ETAT_ACHAT"='hors service' OR "ETAT_ACHAT"='en stock' OR "ETAT_ACHAT"='en attente') ENABLE;
  ALTER TABLE "SMARTOIL"."MACHINES" ADD CONSTRAINT "MACHINES_CHK1" CHECK (categorie IN ( 'presse', 'moteur', 'filtre', 'capteur', 'pompe', 'compresseur', 'convoyeur', 'valve')) ENABLE;
  ALTER TABLE "SMARTOIL"."MACHINES" ADD CONSTRAINT "MACHINES_PK" PRIMARY KEY ("ID_MACHINE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SMARTOIL"."MACHINES" MODIFY ("ID_MACHINE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table UTILISER
--------------------------------------------------------

  ALTER TABLE "SMARTOIL"."UTILISER" ADD CONSTRAINT "UTILISER_PK" PRIMARY KEY ("ID_MATRIEL", "ID_EQUIPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SMARTOIL"."UTILISER" MODIFY ("ID_MATRIEL" NOT NULL ENABLE);
  ALTER TABLE "SMARTOIL"."UTILISER" MODIFY ("ID_EQUIPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "SMARTOIL"."EMPLOYE" ADD CONSTRAINT "EMPLOYE_FK1" FOREIGN KEY ("ID_EQUIPE")
	  REFERENCES "SMARTOIL"."EQUIPE" ("ID_EQUIPE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMENDE
--------------------------------------------------------

  ALTER TABLE "SMARTOIL"."COMMENDE" ADD CONSTRAINT "COMMENDE_FK1" FOREIGN KEY ("ID_CLIENT")
	  REFERENCES "SMARTOIL"."CLIENT" ("ID_CLIENT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "SMARTOIL"."CLIENT" ADD CONSTRAINT "CLIENTS_FK1" FOREIGN KEY ("ID_EMPLOYE")
	  REFERENCES "SMARTOIL"."EMPLOYE" ("ID_EMPLOYE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MACHINES
--------------------------------------------------------

  ALTER TABLE "SMARTOIL"."MACHINES" ADD CONSTRAINT "MACHINES_FK1" FOREIGN KEY ("ID_LABO")
	  REFERENCES "SMARTOIL"."LABO" ("ID_LABO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table UTILISER
--------------------------------------------------------

  ALTER TABLE "SMARTOIL"."UTILISER" ADD CONSTRAINT "UTILISER_FK1" FOREIGN KEY ("ID_EQUIPE")
	  REFERENCES "SMARTOIL"."EMPLOYE" ("ID_EMPLOYE") ENABLE;
  ALTER TABLE "SMARTOIL"."UTILISER" ADD CONSTRAINT "UTILISER_FK2" FOREIGN KEY ("ID_MATRIEL")
	  REFERENCES "SMARTOIL"."MACHINES" ("ID_MACHINE") ENABLE;
