--------------------------------------------------------
--  Fichier cr�� - dimanche-mars-29-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CLIENT
--------------------------------------------------------

  CREATE TABLE "AYOUB"."CLIENT" 
   (	"ID_CLIENT" NUMBER, 
	"NOM_CLIENT" VARCHAR2(100 BYTE), 
	"T�L�PHONE" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"ADRESSE" VARCHAR2(200 BYTE), 
	"TYPE_CLIENT" VARCHAR2(20 BYTE), 
	"STATUT" VARCHAR2(20 BYTE), 
	"ID_EMPLOYE" NUMBER, 
	"TYPE" VARCHAR2(20 BYTE), 
	"TEL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table COMMANDE
--------------------------------------------------------

  CREATE TABLE "AYOUB"."COMMANDE" 
   (	"ID_COMMANDE" NUMBER, 
	"LIBELLE" VARCHAR2(100 BYTE), 
	"DATE_ARRIVAGE" DATE, 
	"DATE_SORTIE" DATE, 
	"ETAT" VARCHAR2(20 BYTE), 
	"QUANTITE" NUMBER, 
	"MONTANT_TOTAL" NUMBER, 
	"ID_CLIENT" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYE
--------------------------------------------------------

  CREATE TABLE "AYOUB"."EMPLOYE" 
   (	"ID_EMPLOYE" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"PRENOM" VARCHAR2(20 BYTE), 
	"AGE" NUMBER, 
	"SALAIRE" NUMBER, 
	"POSTE" VARCHAR2(20 BYTE), 
	"ANCIENNETE" NUMBER, 
	"DISPONIBILITE" VARCHAR2(20 BYTE), 
	"HEURES_TRAVAIL" NUMBER, 
	"FOURNISSEURS_TRAITES" NUMBER, 
	"ID_EQUIPE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EQUIPE
--------------------------------------------------------

  CREATE TABLE "AYOUB"."EQUIPE" 
   (	"ID_EQUIPE" NUMBER, 
	"NOM_EQUIPE" VARCHAR2(20 BYTE), 
	"SPECIALITE" VARCHAR2(20 BYTE), 
	"NBRE_MEMBRES" NUMBER, 
	"ETAT" VARCHAR2(20 BYTE), 
	"RATE" NUMBER, 
	"CHEF_EQUIPE" VARCHAR2(100 BYTE), 
	"NB_MEMBRES" NUMBER DEFAULT 0, 
	"ETAT_EQUIPE" VARCHAR2(20 BYTE) DEFAULT 'Actif'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LABO
--------------------------------------------------------

  CREATE TABLE "AYOUB"."LABO" 
   (	"ID_LABO" NUMBER, 
	"NOM_LABO" VARCHAR2(20 BYTE), 
	"RESULTATS" VARCHAR2(200 BYTE), 
	"CONFORMITE" CHAR(3 BYTE), 
	"ADRESSE" VARCHAR2(200 BYTE), 
	"ESPACE_LABO" NUMBER, 
	"ESPACE_RESTE" NUMBER, 
	"REVIEW" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MACHINES
--------------------------------------------------------

  CREATE TABLE "AYOUB"."MACHINES" 
   (	"ID_MACHINE" NUMBER, 
	"NOM" VARCHAR2(20 BYTE), 
	"CATEGORIE" VARCHAR2(20 BYTE), 
	"REFERENCE" VARCHAR2(20 BYTE), 
	"DATE_ACHAT" DATE, 
	"ETAT_ACHAT" VARCHAR2(20 BYTE), 
	"LOCALISATION" VARCHAR2(150 BYTE), 
	"DATE_FIN_GARENTIE" DATE, 
	"ID_LABO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUIT
--------------------------------------------------------

  CREATE TABLE "AYOUB"."PRODUIT" 
   (	"ID_PRODUIT" NUMBER, 
	"LIBELLE" VARCHAR2(100 BYTE), 
	"QUANTITE" NUMBER DEFAULT 0, 
	"PRIX_UNITAIRE" NUMBER(10,2), 
	"STOCK" NUMBER DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table QUERY_LOG
--------------------------------------------------------

  CREATE TABLE "AYOUB"."QUERY_LOG" 
   (	"QUERY_TEXT" VARCHAR2(1000 BYTE), 
	"ERROR_CODE" VARCHAR2(100 BYTE), 
	"QUERY_TIME" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table UTILISER
--------------------------------------------------------

  CREATE TABLE "AYOUB"."UTILISER" 
   (	"ID_EQUIPE" NUMBER, 
	"ID_MATRIEL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into AYOUB.CLIENT
SET DEFINE OFF;
Insert into AYOUB.CLIENT (ID_CLIENT,NOM_CLIENT,"T�L�PHONE",EMAIL,ADRESSE,TYPE_CLIENT,STATUT,ID_EMPLOYE,TYPE,TEL) values ('1','Mohamed Ali',null,'m.ali@email.com','Tunis',null,'Actif',null,'Particulier','98 123 456');
Insert into AYOUB.CLIENT (ID_CLIENT,NOM_CLIENT,"T�L�PHONE",EMAIL,ADRESSE,TYPE_CLIENT,STATUT,ID_EMPLOYE,TYPE,TEL) values ('2','Fatima Ben Said',null,'f.bensaid@email.com','Sfax',null,'Actif',null,'Entreprise','98 234 567');
Insert into AYOUB.CLIENT (ID_CLIENT,NOM_CLIENT,"T�L�PHONE",EMAIL,ADRESSE,TYPE_CLIENT,STATUT,ID_EMPLOYE,TYPE,TEL) values ('3','Ahmed Jmal',null,'a.jmal@email.com','Sousse',null,'Actif',null,'Particulier','98 345 678');
Insert into AYOUB.CLIENT (ID_CLIENT,NOM_CLIENT,"T�L�PHONE",EMAIL,ADRESSE,TYPE_CLIENT,STATUT,ID_EMPLOYE,TYPE,TEL) values ('4','Leila Chedly',null,'l.chedly@email.com','Monastir',null,'Actif',null,'Entreprise','98 456 789');
Insert into AYOUB.CLIENT (ID_CLIENT,NOM_CLIENT,"T�L�PHONE",EMAIL,ADRESSE,TYPE_CLIENT,STATUT,ID_EMPLOYE,TYPE,TEL) values ('5','Sami Trabelsi',null,'s.trabelsi@email.com','Bizerte',null,'Actif',null,'Particulier','98 567 890');
REM INSERTING into AYOUB.COMMANDE
SET DEFINE OFF;
Insert into AYOUB.COMMANDE (ID_COMMANDE,LIBELLE,DATE_ARRIVAGE,DATE_SORTIE,ETAT,QUANTITE,MONTANT_TOTAL,ID_CLIENT) values ('1','Huile d''olive vierge',to_date('15/02/26','DD/MM/RR'),to_date('20/02/26','DD/MM/RR'),'validee','100','1500','1');
Insert into AYOUB.COMMANDE (ID_COMMANDE,LIBELLE,DATE_ARRIVAGE,DATE_SORTIE,ETAT,QUANTITE,MONTANT_TOTAL,ID_CLIENT) values ('2','Huile d''olive extra vierge',to_date('10/02/26','DD/MM/RR'),to_date('15/02/26','DD/MM/RR'),'validee','50','1250','2');
Insert into AYOUB.COMMANDE (ID_COMMANDE,LIBELLE,DATE_ARRIVAGE,DATE_SORTIE,ETAT,QUANTITE,MONTANT_TOTAL,ID_CLIENT) values ('3','Huile d''argan',to_date('01/03/26','DD/MM/RR'),null,'en cours','30','900','3');
Insert into AYOUB.COMMANDE (ID_COMMANDE,LIBELLE,DATE_ARRIVAGE,DATE_SORTIE,ETAT,QUANTITE,MONTANT_TOTAL,ID_CLIENT) values ('4','Huile de tournesol',to_date('05/03/26','DD/MM/RR'),null,'prete','200','800','4');
Insert into AYOUB.COMMANDE (ID_COMMANDE,LIBELLE,DATE_ARRIVAGE,DATE_SORTIE,ETAT,QUANTITE,MONTANT_TOTAL,ID_CLIENT) values ('5','Huile de noix',to_date('15/01/26','DD/MM/RR'),to_date('20/01/26','DD/MM/RR'),'annulee','75','1125','5');
Insert into AYOUB.COMMANDE (ID_COMMANDE,LIBELLE,DATE_ARRIVAGE,DATE_SORTIE,ETAT,QUANTITE,MONTANT_TOTAL,ID_CLIENT) values ('6','Huile de s�same',to_date('25/02/26','DD/MM/RR'),null,'en cours','120','1800','1');
Insert into AYOUB.COMMANDE (ID_COMMANDE,LIBELLE,DATE_ARRIVAGE,DATE_SORTIE,ETAT,QUANTITE,MONTANT_TOTAL,ID_CLIENT) values ('7','Huile de lin',to_date('05/02/26','DD/MM/RR'),to_date('10/02/26','DD/MM/RR'),'validee','85','1275','2');
Insert into AYOUB.COMMANDE (ID_COMMANDE,LIBELLE,DATE_ARRIVAGE,DATE_SORTIE,ETAT,QUANTITE,MONTANT_TOTAL,ID_CLIENT) values ('8','Huile d''olive bio',to_date('10/03/26','DD/MM/RR'),null,'prete','150','2250','3');
REM INSERTING into AYOUB.EMPLOYE
SET DEFINE OFF;
REM INSERTING into AYOUB.EQUIPE
SET DEFINE OFF;
Insert into AYOUB.EQUIPE (ID_EQUIPE,NOM_EQUIPE,SPECIALITE,NBRE_MEMBRES,ETAT,RATE,CHEF_EQUIPE,NB_MEMBRES,ETAT_EQUIPE) values ('1','?quipe Maintenance','maintenance',null,null,null,'Ahmed Mansouri','5','Actif');
Insert into AYOUB.EQUIPE (ID_EQUIPE,NOM_EQUIPE,SPECIALITE,NBRE_MEMBRES,ETAT,RATE,CHEF_EQUIPE,NB_MEMBRES,ETAT_EQUIPE) values ('2','?quipe Production','production',null,null,null,'Sofia Ben Ahmed','8','Actif');
Insert into AYOUB.EQUIPE (ID_EQUIPE,NOM_EQUIPE,SPECIALITE,NBRE_MEMBRES,ETAT,RATE,CHEF_EQUIPE,NB_MEMBRES,ETAT_EQUIPE) values ('3','?quipe Qualit�','backoffice',null,null,null,'Karim Trabelsi','4','Actif');
Insert into AYOUB.EQUIPE (ID_EQUIPE,NOM_EQUIPE,SPECIALITE,NBRE_MEMBRES,ETAT,RATE,CHEF_EQUIPE,NB_MEMBRES,ETAT_EQUIPE) values ('4','?quipe M�canique','mecanique',null,null,'4,5','Nadia Khalil','6','Actif');
Insert into AYOUB.EQUIPE (ID_EQUIPE,NOM_EQUIPE,SPECIALITE,NBRE_MEMBRES,ETAT,RATE,CHEF_EQUIPE,NB_MEMBRES,ETAT_EQUIPE) values ('5','?quipe Back-office','backoffice',null,null,'4,8','Hassen Karoui','3','Actif');
REM INSERTING into AYOUB.LABO
SET DEFINE OFF;
Insert into AYOUB.LABO (ID_LABO,NOM_LABO,RESULTATS,CONFORMITE,ADRESSE,ESPACE_LABO,ESPACE_RESTE,REVIEW) values ('1','Labo Qualit� Huile','Conforme aux normes ISO','oui','Zone Industrielle, Tunis','150','50','9');
Insert into AYOUB.LABO (ID_LABO,NOM_LABO,RESULTATS,CONFORMITE,ADRESSE,ESPACE_LABO,ESPACE_RESTE,REVIEW) values ('2','Labo Recherche','Analyses en cours','non','Cit� Technologique, Sfax','200','30','7');
Insert into AYOUB.LABO (ID_LABO,NOM_LABO,RESULTATS,CONFORMITE,ADRESSE,ESPACE_LABO,ESPACE_RESTE,REVIEW) values ('3','Labo Contr�le','R�sultats satisfaisants','oui','Parc Industriel, Sousse','120','40','8');
Insert into AYOUB.LABO (ID_LABO,NOM_LABO,RESULTATS,CONFORMITE,ADRESSE,ESPACE_LABO,ESPACE_RESTE,REVIEW) values ('4','Labo D�veloppement','En d�veloppement','non','Technopole, Monastir','180','60','6');
Insert into AYOUB.LABO (ID_LABO,NOM_LABO,RESULTATS,CONFORMITE,ADRESSE,ESPACE_LABO,ESPACE_RESTE,REVIEW) values ('5','Labo Analyse','Conforme aux exigences','oui','Zone Franche, Bizerte','250','100','10');
REM INSERTING into AYOUB.MACHINES
SET DEFINE OFF;
REM INSERTING into AYOUB.PRODUIT
SET DEFINE OFF;
REM INSERTING into AYOUB.QUERY_LOG
SET DEFINE OFF;
REM INSERTING into AYOUB.UTILISER
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index CLIENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AYOUB"."CLIENTS_PK" ON "AYOUB"."CLIENT" ("ID_CLIENT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index COMMENDE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AYOUB"."COMMENDE_PK" ON "AYOUB"."COMMANDE" ("ID_COMMANDE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLOYE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AYOUB"."EMPLOYE_PK" ON "AYOUB"."EMPLOYE" ("ID_EMPLOYE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TABLE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AYOUB"."TABLE_PK" ON "AYOUB"."EQUIPE" ("ID_EQUIPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AYOUB"."TABLE1_PK" ON "AYOUB"."LABO" ("ID_LABO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MACHINES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AYOUB"."MACHINES_PK" ON "AYOUB"."MACHINES" ("ID_MACHINE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SYS_C007526
--------------------------------------------------------

  CREATE UNIQUE INDEX "AYOUB"."SYS_C007526" ON "AYOUB"."PRODUIT" ("ID_PRODUIT") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UTILISER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AYOUB"."UTILISER_PK" ON "AYOUB"."UTILISER" ("ID_MATRIEL", "ID_EQUIPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "AYOUB"."CLIENT" ADD CONSTRAINT "CLIENT_STATUT_CHECK" CHECK (STATUT IN ('Actif', 'Inactif', 'En attente')) ENABLE;
  ALTER TABLE "AYOUB"."CLIENT" ADD CONSTRAINT "CLIENT_TYPE_CHECK" CHECK (TYPE IN ('Particulier', 'Entreprise')) ENABLE;
  ALTER TABLE "AYOUB"."CLIENT" ADD CONSTRAINT "CLIENTS_PK" PRIMARY KEY ("ID_CLIENT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AYOUB"."CLIENT" MODIFY ("ID_CLIENT" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table COMMANDE
--------------------------------------------------------

  ALTER TABLE "AYOUB"."COMMANDE" ADD CONSTRAINT "COMMANDE_ETAT_CHECK" CHECK (ETAT IN ('en cours','validee','prete','annulee','livree')) ENABLE;
  ALTER TABLE "AYOUB"."COMMANDE" ADD CONSTRAINT "COMMENDE_PK" PRIMARY KEY ("ID_COMMANDE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AYOUB"."COMMANDE" MODIFY ("ID_COMMANDE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "AYOUB"."EMPLOYE" ADD CONSTRAINT "EMPLOYE_CHK2" CHECK (poste IN ('Admin', 'Manager', 'client')) ENABLE;
  ALTER TABLE "AYOUB"."EMPLOYE" ADD CONSTRAINT "EMPLOYE_CHK1" CHECK (disponibilite IN ('actif', 'suspendu')) ENABLE;
  ALTER TABLE "AYOUB"."EMPLOYE" ADD CONSTRAINT "EMPLOYE_PK" PRIMARY KEY ("ID_EMPLOYE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AYOUB"."EMPLOYE" MODIFY ("ID_EMPLOYE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EQUIPE
--------------------------------------------------------

  ALTER TABLE "AYOUB"."EQUIPE" MODIFY ("NOM_EQUIPE" NOT NULL ENABLE);
  ALTER TABLE "AYOUB"."EQUIPE" ADD CONSTRAINT "EQUIPE_CHK2" CHECK (etat IN ('active','inactive')) ENABLE;
  ALTER TABLE "AYOUB"."EQUIPE" ADD CONSTRAINT "EQUIPE_CHK1" CHECK (specialite IN ('maintenance','production','mecanique','backoffice')) ENABLE;
  ALTER TABLE "AYOUB"."EQUIPE" ADD CONSTRAINT "TABLE_PK" PRIMARY KEY ("ID_EQUIPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AYOUB"."EQUIPE" MODIFY ("SPECIALITE" NOT NULL ENABLE);
  ALTER TABLE "AYOUB"."EQUIPE" MODIFY ("ID_EQUIPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LABO
--------------------------------------------------------

  ALTER TABLE "AYOUB"."LABO" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ID_LABO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AYOUB"."LABO" ADD CONSTRAINT "TABLE1_CHK1" CHECK ("CONFORMITE"='oui' OR "CONFORMITE"='non') ENABLE;
  ALTER TABLE "AYOUB"."LABO" MODIFY ("CONFORMITE" NOT NULL ENABLE);
  ALTER TABLE "AYOUB"."LABO" MODIFY ("NOM_LABO" NOT NULL ENABLE);
  ALTER TABLE "AYOUB"."LABO" MODIFY ("ID_LABO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MACHINES
--------------------------------------------------------

  ALTER TABLE "AYOUB"."MACHINES" MODIFY ("ID_LABO" NOT NULL ENABLE);
  ALTER TABLE "AYOUB"."MACHINES" ADD CONSTRAINT "MACHINES_CHK2" CHECK ("ETAT_ACHAT"='en service' OR "ETAT_ACHAT"='panne' OR "ETAT_ACHAT"='maintenance' OR "ETAT_ACHAT"='hors service' OR "ETAT_ACHAT"='en stock' OR "ETAT_ACHAT"='en attente') ENABLE;
  ALTER TABLE "AYOUB"."MACHINES" ADD CONSTRAINT "MACHINES_CHK1" CHECK (categorie IN ( 'presse', 'moteur', 'filtre', 'capteur', 'pompe', 'compresseur', 'convoyeur', 'valve')) ENABLE;
  ALTER TABLE "AYOUB"."MACHINES" ADD CONSTRAINT "MACHINES_PK" PRIMARY KEY ("ID_MACHINE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AYOUB"."MACHINES" MODIFY ("ID_MACHINE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUIT
--------------------------------------------------------

  ALTER TABLE "AYOUB"."PRODUIT" ADD PRIMARY KEY ("ID_PRODUIT")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AYOUB"."PRODUIT" MODIFY ("LIBELLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table UTILISER
--------------------------------------------------------

  ALTER TABLE "AYOUB"."UTILISER" ADD CONSTRAINT "UTILISER_PK" PRIMARY KEY ("ID_MATRIEL", "ID_EQUIPE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AYOUB"."UTILISER" MODIFY ("ID_MATRIEL" NOT NULL ENABLE);
  ALTER TABLE "AYOUB"."UTILISER" MODIFY ("ID_EQUIPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CLIENT
--------------------------------------------------------

  ALTER TABLE "AYOUB"."CLIENT" ADD CONSTRAINT "CLIENTS_FK1" FOREIGN KEY ("ID_EMPLOYE")
	  REFERENCES "AYOUB"."EMPLOYE" ("ID_EMPLOYE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMMANDE
--------------------------------------------------------

  ALTER TABLE "AYOUB"."COMMANDE" ADD CONSTRAINT "COMMENDE_FK1" FOREIGN KEY ("ID_CLIENT")
	  REFERENCES "AYOUB"."CLIENT" ("ID_CLIENT") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYE
--------------------------------------------------------

  ALTER TABLE "AYOUB"."EMPLOYE" ADD CONSTRAINT "EMPLOYE_FK1" FOREIGN KEY ("ID_EQUIPE")
	  REFERENCES "AYOUB"."EQUIPE" ("ID_EQUIPE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MACHINES
--------------------------------------------------------

  ALTER TABLE "AYOUB"."MACHINES" ADD CONSTRAINT "MACHINES_FK1" FOREIGN KEY ("ID_LABO")
	  REFERENCES "AYOUB"."LABO" ("ID_LABO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table UTILISER
--------------------------------------------------------

  ALTER TABLE "AYOUB"."UTILISER" ADD CONSTRAINT "UTILISER_FK1" FOREIGN KEY ("ID_EQUIPE")
	  REFERENCES "AYOUB"."EMPLOYE" ("ID_EMPLOYE") ENABLE;
  ALTER TABLE "AYOUB"."UTILISER" ADD CONSTRAINT "UTILISER_FK2" FOREIGN KEY ("ID_MATRIEL")
	  REFERENCES "AYOUB"."MACHINES" ("ID_MACHINE") ENABLE;
